# Generated by Django 6.0.2 on 2026-02-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('barber', 'Barbero'), ('client', 'Cliente'), ('consultant', 'Consultor')], default='client', max_length=15),
        ),
    ]
