# Generated by Django 6.0.2 on 2026-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superusuario'), ('admin', 'Administrador'), ('barber', 'Barbero'), ('client', 'Cliente')], default='client', max_length=15),
        ),
    ]
