# Generated by Django 6.0.2 on 2026-09-16 20:21

from django.db import migrations, models


def nullify_empty_email_phone(apps, schema_editor):
    """
    Convierte '' a NULL en email/phone antes de aplicar el UNIQUE:
    Postgres trata varias filas con '' como duplicados, pero permite
    múltiples NULL sin problema.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='').update(email=None)
    User.objects.filter(phone='').update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        # 1) Permitir NULL primero (la columna original era NOT NULL).
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        # 2) Ahora sí se puede limpiar los '' duplicados a NULL.
        migrations.RunPython(nullify_empty_email_phone, migrations.RunPython.noop),
        # 3) Y finalmente aplicar el UNIQUE sin que choque con ellos.
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
