# Generated by Django 6.0.2 on 2026-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_alter_service_options_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enlace de imagen del servicio'),
        ),
    ]
