# Generated by Django 6.0.2 on 2026-09-17 14:04

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    Appointment.objects.filter(status__in=['pending', 'confirmed']).update(status='scheduled')
    Appointment.objects.filter(status='cancelled').update(status='cancelled_barber')


def reverse_migrate_old_statuses(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    Appointment.objects.filter(status='scheduled').update(status='pending')
    Appointment.objects.filter(status__in=['cancelled_client', 'cancelled_barber']).update(status='cancelled')


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_barber', 'Cancelada por barbero'), ('completed', 'Completada')], default='scheduled', max_length=20),
        ),
        migrations.RunPython(migrate_old_statuses, reverse_migrate_old_statuses),
    ]
